# The Makefile is not working due to problems with 'multiple definitions'
# But the program is bulding correctly with the Arduino IDE

ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

# change this directory where do you have the custom libraries
USER_LIB_PATH = /home/user/Arduino/libraries/
BOARD_TAG = mega2560

ARDUINO_LIBS = SD SPI SoftwareSerial Adafruit_Fingerprint_Sensor_Library Wire

include /usr/share/arduino/Arduino.mk 
