ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

# change this directory where do you have the custom libraries
USER_LIB_PATH = /home/user/Arduino/libraries/
BOARD_TAG = mega2560

ARDUINO_LIBS = SoftwareSerial Servo Adafruit_Fingerprint_Sensor_Library SPI SD

include /usr/share/arduino/Arduino.mk 
